### ISSUE TITLE
Astro bot Idea 

### ISSUE THREAD

**Issue by ghost** [vihangayt0/Astro-MD-V7#72]
තව කමාන්ඩ් ටිකක් ඇඩ් කරානම් මරු,ගෘප් වලින් කික් කරන්නයි ඇඩ් කරන්නයි වගේ ගොඩක් දේවල්,සමහර කමාන්ඩ් වැඩත් නෑ ඒවා ෆික්ස් කරලා ගත්තනම් නියමයි

**Comment by vihangayt0** [comment]
Elama
